### ISSUE TITLE
Connect ESP32-S2 Error: Timeout

### ISSUE THREAD

**Issue by 466034505** [OpenBuilds/firmwaretool#1]
esptool.js v0.1-dev
Serial port WebSerial VendorID 0x303a ProductID 0x2
Connecting.........._
Detecting chip type... ESP32-S2
Chip is ESP32-S2
Features: Wi-Fi
Crystal is 40MHz
MAC: 68:67:25:2d:f4:0c
Uploading stub...
Error: Timeout

**Comment by petervanderwalt** [comment]
This is an internal-use tool still in development

Please use https://github.com/espressif/esptool-js/ for your own use cases thanks
